# Copyright (c) 2022-present Bytebase (Hong Kong) Limited.
#
# Portions of this software are licensed as follows:
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
name: Build release artifacts and draft release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  build-linux-binary:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --skip=publish --config ci/goreleaser-for-linux.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: cy-linux
          path: dist/cy*
  build-darwin-binary:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Build
        uses: goreleaser/goreleaser-action@v5
        with:
          #args: release --skip=publish --config ci/goreleaser-for-darwin.yaml
          args: release --config ci/goreleaser-for-darwin.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: cy-darwin
          path: dist/cy*
  draft-release:
    needs: [build-linux-binary, build-darwin-binary]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - name: Make directories
        run: |
          mkdir -p ./cy-build/linux
          mkdir -p ./cy-build/darwin
      - name: Download linux binaries
        uses: actions/download-artifact@v3
        with:
          name: cy-linux
          path: ./cy-build/linux
      - name: Download darwin binaries
        uses: actions/download-artifact@v3
        with:
          name: cy-darwin
          path: ./cy-build/darwin
      - name: Merge checksum file
        run: |
          cd ./cy-build
          cat ./darwin/cy*checksums.txt >> checksums.txt
          cat ./linux/cy*checksums.txt >> checksums.txt
          rm ./darwin/cy*checksums.txt
          rm ./linux/cy*checksums.txt
      - name: Release
        uses: goreleaser/goreleaser-action@v5
        with:
          args: release --config ci/goreleaser-release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
